In [7]:
import tensorflow as tf
from transformers import AutoTokenizer, TFBertForPreTraining

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
model = TFBertForPreTraining.from_pretrained("bert-base-uncased")
input_ids = tokenizer("some text here", add_special_tokens=True, return_tensors="tf")

outputs = model(input_ids)
print("outputs[:2] is", outputs[:2])
print("outputs[:2] end")
prediction_logits, seq_relationship_logits = outputs[:2]
print("prediction_logits is", prediction_logits)

All model checkpoint layers were used when initializing TFBertForPreTraining.

All the layers of TFBertForPreTraining were initialized from the model checkpoint at bert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForPreTraining for predictions without further training.


outputs[:2] is (<tf.Tensor: shape=(1, 5, 30522), dtype=float32, numpy=
array([[[ -6.8795724,  -6.7815495,  -6.76966  , ...,  -6.0176024,
          -6.0539203,  -4.2974057],
        [-11.962255 , -11.882247 , -11.932658 , ..., -11.1073065,
         -10.714809 ,  -8.544879 ],
        [-11.211011 , -11.585727 , -11.226399 , ..., -10.958972 ,
         -10.400204 ,  -9.247572 ],
        [-12.922968 , -12.618054 , -12.969504 , ..., -13.228766 ,
         -12.073488 ,  -8.925045 ],
        [-12.097216 , -11.819663 , -11.771928 , ...,  -9.71159  ,
         -10.45709  ,  -9.606064 ]]], dtype=float32)>, <tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[ 3.692657 , -2.5917392]], dtype=float32)>)
outputs[:2] end
prediction_logits is tf.Tensor(
[[[ -6.8795724  -6.7815495  -6.76966   ...  -6.0176024  -6.0539203
    -4.2974057]
  [-11.962255  -11.882247  -11.932658  ... -11.1073065 -10.714809
    -8.544879 ]
  [-11.211011  -11.585727  -11.226399  ... -10.958972  -10.400204
    -9.247572 ]
  [-12.